- name: Create database
  mysql_db:
    login_user: root
    login_password: '{{ guacamole_mysql_root_password }}'
    name: '{{ guacamole_db_name }}'
    encoding: utf8
    collation: utf8_general_ci
    state: present

- name: Create database user
  mysql_user:
    login_user: root
    login_password: '{{ guacamole_mysql_root_password }}'
    name: '{{ guacamole_db_username }}'
    password: '{{ guacamole_db_password }}'
    priv: '{{ guacamole_db_name }}.*:ALL'

- name: Check database schema
  shell: >
    mysql --user={{ guacamole_db_username }} \
    --password={{ guacamole_db_password }} \
    {{ guacamole_db_name }} \
    --host=localhost \
    --execute="select * from guacamole_system_permission"
  register: check_table_exists
  failed_when: check_table_exists.stderr.find('guacamole_system_permission\' doesn\'t exist') == -1 and check_table_exists.stderr != ""
  changed_when: False

- name: Make sure guacamole-auth-jdbc-mysql is downloaded
  unarchive:
    src: 'http://apache.mirrors.tds.net/incubator/guacamole/{{ guacamole_version }}/binary/guacamole-auth-jdbc-{{ guacamole_version }}.tar.gz'
    remote_src: yes
    dest: '{{ guacamole_temp_path }}'
    creates: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-{{ guacamole_version }}/mysql/guacamole-auth-jdbc-mysql-{{ guacamole_version }}.jar'
  when: check_table_exists.stderr.find('guacamole_system_permission\' doesn\'t exist') != -1

- name: Create database schema
  mysql_db:
    login_user: '{{ guacamole_db_username }}'
    login_password: '{{ guacamole_db_password }}'
    name: '{{ guacamole_db_name }}'
    state: import
    target: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-{{ guacamole_version }}/mysql/schema/001-create-schema.sql'
  when: check_table_exists.stderr.find('guacamole_system_permission\' doesn\'t exist') != -1

- name: Create guacamole admin user
  mysql_db:
    login_user: '{{ guacamole_db_username }}'
    login_password: '{{ guacamole_db_password }}'
    name: '{{ guacamole_db_name }}'
    state: import
    target: '{{ guacamole_temp_path }}/guacamole-auth-jdbc-{{ guacamole_version }}/mysql/schema/002-create-admin-user.sql'
  when: check_table_exists.stderr.find('guacamole_system_permission\' doesn\'t exist') != -1
