- name: Install epel repository
  yum:
    name: epel-release
    state: present

- name: Add necessary repository
  yum:
    name: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
    state: present

- name: Install necessary packages
  yum:
    name: '{{ item.package }}'
    state: present
  with_items: "{{ guacamole_packages_EL }}"
